-- Run as ACCOUNTADMIN. Adjust user names before GRANT ROLE statements.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS BI_ANALYST;
CREATE ROLE IF NOT EXISTS SECURITY_ADMIN;

GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE DATA_ANALYST TO ROLE SYSADMIN;
GRANT ROLE DATA_SCIENTIST TO ROLE SYSADMIN;
GRANT ROLE BI_ANALYST TO ROLE SYSADMIN;
GRANT ROLE SECURITY_ADMIN TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE GLOBRORETAIL_DW TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE GLOBRORETAIL_DW TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE GLOBRORETAIL_DW TO ROLE DATA_SCIENTIST;
GRANT USAGE ON DATABASE GLOBRORETAIL_DW TO ROLE BI_ANALYST;
GRANT USAGE ON DATABASE GLOBRORETAIL_DW TO ROLE SECURITY_ADMIN;

GRANT USAGE ON SCHEMA GLOBRORETAIL_DW.CORE TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA GLOBRORETAIL_DW.CORE TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA GLOBRORETAIL_DW.CORE TO ROLE DATA_SCIENTIST;
GRANT USAGE ON SCHEMA GLOBRORETAIL_DW.CORE TO ROLE BI_ANALYST;
GRANT USAGE ON SCHEMA GLOBRORETAIL_DW.SECURITY TO ROLE SECURITY_ADMIN;
GRANT USAGE ON SCHEMA GLOBRORETAIL_DW.ANALYTICS TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA GLOBRORETAIL_DW.ANALYTICS TO ROLE DATA_SCIENTIST;
GRANT USAGE ON SCHEMA GLOBRORETAIL_DW.ANALYTICS TO ROLE BI_ANALYST;

GRANT USAGE ON WAREHOUSE GR_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE GR_TRANSFORM_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE GR_BI_WH TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE GR_BI_WH TO ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE GR_BI_WH TO ROLE BI_ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA GLOBRORETAIL_DW.CORE TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GLOBRORETAIL_DW.CORE TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA GLOBRORETAIL_DW.CORE TO ROLE BI_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA GLOBRORETAIL_DW.SECURITY TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA GLOBRORETAIL_DW.SECURITY TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL VIEWS IN SCHEMA GLOBRORETAIL_DW.SECURITY TO ROLE BI_ANALYST;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GLOBRORETAIL_DW.RAW TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GLOBRORETAIL_DW.CLEAN TO ROLE DATA_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA GLOBRORETAIL_DW.CORE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GLOBRORETAIL_DW.OPS TO ROLE DATA_ENGINEER;

-- Future grants keep access aligned for new tables/views.
GRANT SELECT ON FUTURE TABLES IN SCHEMA GLOBRORETAIL_DW.CORE TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GLOBRORETAIL_DW.CORE TO ROLE DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GLOBRORETAIL_DW.CORE TO ROLE BI_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GLOBRORETAIL_DW.SECURITY TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GLOBRORETAIL_DW.SECURITY TO ROLE DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GLOBRORETAIL_DW.SECURITY TO ROLE BI_ANALYST;

-- Example user assignment; replace USER_NAME before execution.
-- GRANT ROLE DATA_ENGINEER TO USER <USER_NAME>;
