USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA SECURITY;

CREATE OR REPLACE MASKING POLICY MP_CUSTOMER_EMAIL AS (VAL STRING) RETURNS STRING ->
CASE
  WHEN CURRENT_ROLE() IN ('SECURITY_ADMIN','DATA_ENGINEER') THEN VAL
  WHEN CURRENT_ROLE() = 'DATA_SCIENTIST' THEN REGEXP_REPLACE(VAL, '(^.).*(@.*$)', '\\1***\\2')
  ELSE '********@masked'
END;

CREATE OR REPLACE MASKING POLICY MP_PHONE AS (VAL STRING) RETURNS STRING ->
CASE
  WHEN CURRENT_ROLE() IN ('SECURITY_ADMIN','DATA_ENGINEER') THEN VAL
  ELSE '***********'
END;

CREATE OR REPLACE MASKING POLICY MP_CARD_HASH AS (VAL STRING) RETURNS STRING ->
CASE
  WHEN CURRENT_ROLE() IN ('SECURITY_ADMIN','DATA_ENGINEER') THEN VAL
  ELSE LEFT(VAL,8) || '********'
END;

ALTER TABLE CORE.DIM_CUSTOMER MODIFY COLUMN CUSTOMER_EMAIL SET MASKING POLICY MP_CUSTOMER_EMAIL;
ALTER TABLE CORE.DIM_CUSTOMER MODIFY COLUMN PHONE_NUMBER SET MASKING POLICY MP_PHONE;
ALTER TABLE CORE.DIM_CUSTOMER MODIFY COLUMN PAYMENT_CARD_HASH SET MASKING POLICY MP_CARD_HASH;

CREATE OR REPLACE ROW ACCESS POLICY RAP_STORE_REGION AS (REGION_VALUE STRING) RETURNS BOOLEAN ->
CASE
  WHEN CURRENT_ROLE() IN ('SECURITY_ADMIN','DATA_ENGINEER') THEN TRUE
  WHEN CURRENT_ROLE() = 'BI_ANALYST' THEN REGION_VALUE = 'North'
  WHEN CURRENT_ROLE() = 'DATA_SCIENTIST' THEN REGION_VALUE IN ('North','South')
  WHEN CURRENT_ROLE() = 'DATA_ANALYST' THEN TRUE
  ELSE FALSE
END;

ALTER TABLE CORE.DIM_STORE ADD ROW ACCESS POLICY RAP_STORE_REGION ON (REGION);

CREATE OR REPLACE SECURE VIEW SECURITY.SECURE_V_CUSTOMER AS
SELECT CUSTOMER_KEY,CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SEGMENT,COUNTRY,
       CUSTOMER_EMAIL,PHONE_NUMBER,PAYMENT_CARD_HASH,EFFECTIVE_FROM,EFFECTIVE_TO,IS_CURRENT
FROM CORE.DIM_CUSTOMER
WHERE IS_CURRENT=TRUE;

CREATE OR REPLACE SECURE VIEW SECURITY.SECURE_V_STORE_SALES AS
SELECT s.STORE_ID,s.STORE_NAME,s.CITY,s.STATE,s.COUNTRY,s.REGION,
       COUNT(f.SALES_KEY) AS TRANSACTION_COUNT,
       SUM(f.REVENUE_AMOUNT) AS REVENUE_AMOUNT
FROM CORE.DIM_STORE s
LEFT JOIN CORE.FACT_SALES f ON f.STORE_KEY=s.STORE_KEY
GROUP BY s.STORE_ID,s.STORE_NAME,s.CITY,s.STATE,s.COUNTRY,s.REGION;
