USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA CORE;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  CUSTOMER_ID STRING NOT NULL,
  CUSTOMER_NAME STRING,
  CUSTOMER_SEGMENT STRING,
  COUNTRY STRING,
  CUSTOMER_EMAIL STRING,
  PHONE_NUMBER STRING,
  PAYMENT_CARD_HASH STRING,
  EFFECTIVE_FROM TIMESTAMP_LTZ NOT NULL,
  EFFECTIVE_TO TIMESTAMP_LTZ,
  IS_CURRENT BOOLEAN DEFAULT TRUE,
  RECORD_HASH STRING,
  CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_KEY)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
  PRODUCT_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  PRODUCT_ID STRING NOT NULL,
  PRODUCT_NAME STRING,
  CATEGORY STRING,
  PRICE NUMBER(10,2),
  STATUS STRING,
  EFFECTIVE_FROM TIMESTAMP_LTZ NOT NULL,
  EFFECTIVE_TO TIMESTAMP_LTZ,
  IS_CURRENT BOOLEAN DEFAULT TRUE,
  RECORD_HASH STRING,
  CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (PRODUCT_KEY)
);

CREATE OR REPLACE TABLE DIM_STORE (
  STORE_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  STORE_ID STRING NOT NULL,
  STORE_NAME STRING,
  CITY STRING,
  STATE STRING,
  COUNTRY STRING,
  REGION STRING,
  CONSTRAINT PK_DIM_STORE PRIMARY KEY (STORE_KEY)
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY NUMBER PRIMARY KEY,
  FULL_DATE DATE,
  YEAR NUMBER,
  MONTH NUMBER,
  DAY NUMBER,
  QUARTER NUMBER,
  DAY_OF_WEEK NUMBER,
  DAY_NAME STRING
);

CREATE OR REPLACE TABLE FACT_SALES (
  SALES_KEY NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  SOURCE_TYPE STRING,
  SOURCE_TRANSACTION_ID STRING,
  CUSTOMER_KEY NUMBER,
  PRODUCT_KEY NUMBER,
  STORE_KEY NUMBER,
  DATE_KEY NUMBER,
  SALES_AMOUNT NUMBER(12,2),
  DISCOUNT_AMOUNT NUMBER(12,2),
  TAX_AMOUNT NUMBER(12,2),
  REVENUE_AMOUNT NUMBER(12,2),
  TRANSACTION_DATE DATE,
  LOADED_AT TIMESTAMP_LTZ,
  CONSTRAINT PK_FACT_SALES PRIMARY KEY (SALES_KEY),
  CONSTRAINT FK_CUST FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
  CONSTRAINT FK_PROD FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
  CONSTRAINT FK_STORE FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY),
  CONSTRAINT FK_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY)
);

CREATE OR REPLACE TABLE FACT_INVENTORY (
  INVENTORY_KEY NUMBER AUTOINCREMENT,
  DEVICE_ID STRING,
  STORE_KEY NUMBER,
  PRODUCT_KEY NUMBER,
  QUANTITY_ON_HAND NUMBER,
  LOG_DATE DATE,
  LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE ML_FEATURES_HOURLY_STORE_REVENUE (
  FEATURE_DATE DATE,
  STORE_KEY NUMBER,
  TOTAL_REVENUE NUMBER(18,2),
  TRANSACTION_COUNT NUMBER,
  AVG_TRANSACTION_VALUE NUMBER(18,2),
  LOW_STOCK_EVENTS NUMBER,
  REVENUE_LAG_1_DAY NUMBER(18,2),
  REVENUE_ROLLING_7D NUMBER(18,2),
  ANOMALY_SCORE NUMBER(18,6)
);
