USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA CORE;

-- Store attributes are not present in the supplied source CSVs. These deterministic
-- demo attributes are generated from STORE_ID so the required star schema remains executable.
INSERT OVERWRITE INTO DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, COUNTRY, REGION)
SELECT STORE_ID,
       'GloboRetail Store ' || STORE_ID,
       'City_' || RIGHT(STORE_ID,3),
       'STATE_' || LPAD(TO_VARCHAR(MOD(TRY_TO_NUMBER(RIGHT(STORE_ID,3))-1,20)+1),2,'0'),
       'India',
       CASE MOD(TRY_TO_NUMBER(RIGHT(STORE_ID,3))-1,4)
         WHEN 0 THEN 'North' WHEN 1 THEN 'South' WHEN 2 THEN 'East' ELSE 'West' END
FROM (SELECT DISTINCT STORE_ID FROM RAW.RAW_POS_SALES
      UNION SELECT DISTINCT STORE_ID FROM RAW.RAW_INVENTORY_DEVICE_LOGS);

INSERT OVERWRITE INTO DIM_DATE
SELECT TO_NUMBER(TO_CHAR(D,'YYYYMMDD')),
       D, YEAR(D), MONTH(D), DAY(D), QUARTER(D), DAYOFWEEKISO(D), DAYNAME(D)
FROM (
  SELECT DATEADD(DAY, SEQ4(), '2024-01-01'::DATE) AS D
  FROM TABLE(GENERATOR(ROWCOUNT => 366))
)
WHERE D <= '2024-12-31';
