USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA CORE;

-- Initial/current customer dimension. Source contains only CUSTOMER_ID, so the remaining
-- required customer attributes are deterministic demo enrichments, not claims about real PII.
MERGE INTO DIM_CUSTOMER tgt
USING (
  SELECT CUSTOMER_ID,
         'Customer_' || CUSTOMER_ID AS CUSTOMER_NAME,
         CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),3)
           WHEN 0 THEN 'STANDARD' WHEN 1 THEN 'PREMIUM' ELSE 'BASIC' END AS CUSTOMER_SEGMENT,
         CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),4)
           WHEN 0 THEN 'India' WHEN 1 THEN 'USA' WHEN 2 THEN 'UK' ELSE 'UAE' END AS COUNTRY,
         LOWER(CUSTOMER_ID) || '@example.demo' AS CUSTOMER_EMAIL,
         '+91-90000-' || LPAD(RIGHT(CUSTOMER_ID,5),5,'0') AS PHONE_NUMBER,
         SHA2('CARD-' || CUSTOMER_ID,256) AS PAYMENT_CARD_HASH,
         MD5(CUSTOMER_ID || '|' || CUSTOMER_NAME || '|' || CUSTOMER_SEGMENT || '|' || COUNTRY) AS RECORD_HASH
  FROM (
    SELECT DISTINCT CUSTOMER_ID FROM RAW.RAW_POS_SALES
    UNION
    SELECT DISTINCT CUSTOMER_ID FROM RAW.RAW_ONLINE_ORDERS
  ) s
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID AND tgt.IS_CURRENT = TRUE
WHEN MATCHED AND NVL(tgt.RECORD_HASH,'') <> src.RECORD_HASH THEN
  UPDATE SET EFFECTIVE_TO = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
WHEN NOT MATCHED THEN
  INSERT (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SEGMENT,COUNTRY,CUSTOMER_EMAIL,PHONE_NUMBER,PAYMENT_CARD_HASH,EFFECTIVE_FROM,IS_CURRENT,RECORD_HASH)
  VALUES (src.CUSTOMER_ID,src.CUSTOMER_NAME,src.CUSTOMER_SEGMENT,src.COUNTRY,src.CUSTOMER_EMAIL,src.PHONE_NUMBER,src.PAYMENT_CARD_HASH,CURRENT_TIMESTAMP(),TRUE,src.RECORD_HASH);

-- Reinsert changed current versions after closing the previous version.
INSERT INTO DIM_CUSTOMER (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SEGMENT,COUNTRY,CUSTOMER_EMAIL,PHONE_NUMBER,PAYMENT_CARD_HASH,EFFECTIVE_FROM,IS_CURRENT,RECORD_HASH)
SELECT s.CUSTOMER_ID,s.CUSTOMER_NAME,s.CUSTOMER_SEGMENT,s.COUNTRY,s.CUSTOMER_EMAIL,s.PHONE_NUMBER,s.PAYMENT_CARD_HASH,CURRENT_TIMESTAMP(),TRUE,s.RECORD_HASH
FROM (
  SELECT DISTINCT CUSTOMER_ID,
         'Customer_' || CUSTOMER_ID CUSTOMER_NAME,
         CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),3) WHEN 0 THEN 'STANDARD' WHEN 1 THEN 'PREMIUM' ELSE 'BASIC' END CUSTOMER_SEGMENT,
         CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),4) WHEN 0 THEN 'India' WHEN 1 THEN 'USA' WHEN 2 THEN 'UK' ELSE 'UAE' END COUNTRY,
         LOWER(CUSTOMER_ID) || '@example.demo' CUSTOMER_EMAIL,
         '+91-90000-' || LPAD(RIGHT(CUSTOMER_ID,5),5,'0') PHONE_NUMBER,
         SHA2('CARD-' || CUSTOMER_ID,256) PAYMENT_CARD_HASH,
         MD5(CUSTOMER_ID || '|' || ('Customer_' || CUSTOMER_ID)) RECORD_HASH
  FROM (SELECT DISTINCT CUSTOMER_ID FROM RAW.RAW_POS_SALES UNION SELECT DISTINCT CUSTOMER_ID FROM RAW.RAW_ONLINE_ORDERS)
) s
LEFT JOIN DIM_CUSTOMER c ON c.CUSTOMER_ID=s.CUSTOMER_ID AND c.IS_CURRENT=TRUE
WHERE c.CUSTOMER_KEY IS NULL;

MERGE INTO DIM_PRODUCT tgt
USING (
 SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE, STATUS,
        MD5(PRODUCT_ID||'|'||PRODUCT_NAME||'|'||CATEGORY||'|'||PRICE||'|'||STATUS) RECORD_HASH
 FROM RAW.RAW_PRODUCT_CATALOG
 QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY LOADED_AT DESC)=1
) src
ON tgt.PRODUCT_ID=src.PRODUCT_ID AND tgt.IS_CURRENT=TRUE
WHEN MATCHED AND NVL(tgt.RECORD_HASH,'') <> src.RECORD_HASH THEN
 UPDATE SET EFFECTIVE_TO=CURRENT_TIMESTAMP(), IS_CURRENT=FALSE
WHEN NOT MATCHED THEN
 INSERT (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,EFFECTIVE_FROM,IS_CURRENT,RECORD_HASH)
 VALUES (src.PRODUCT_ID,src.PRODUCT_NAME,src.CATEGORY,src.PRICE,src.STATUS,CURRENT_TIMESTAMP(),TRUE,src.RECORD_HASH);

INSERT INTO DIM_PRODUCT (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,EFFECTIVE_FROM,IS_CURRENT,RECORD_HASH)
SELECT s.PRODUCT_ID,s.PRODUCT_NAME,s.CATEGORY,s.PRICE,s.STATUS,CURRENT_TIMESTAMP(),TRUE,s.RECORD_HASH
FROM (
 SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,RECORD_HASH FROM (
  SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,
         MD5(PRODUCT_ID||'|'||PRODUCT_NAME||'|'||CATEGORY||'|'||PRICE||'|'||STATUS) RECORD_HASH,
         ROW_NUMBER() OVER(PARTITION BY PRODUCT_ID ORDER BY LOADED_AT DESC) RN
  FROM RAW.RAW_PRODUCT_CATALOG) WHERE RN=1
) s LEFT JOIN DIM_PRODUCT p ON p.PRODUCT_ID=s.PRODUCT_ID AND p.IS_CURRENT=TRUE
WHERE p.PRODUCT_KEY IS NULL;
