USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA CORE;

-- POS source has no transaction date. For this source, ingestion date is used as the
-- transaction_date proxy. Online orders retain their source ORDER_DATE.
INSERT INTO FACT_SALES (
 SOURCE_TYPE,SOURCE_TRANSACTION_ID,CUSTOMER_KEY,PRODUCT_KEY,STORE_KEY,DATE_KEY,
 SALES_AMOUNT,DISCOUNT_AMOUNT,TAX_AMOUNT,REVENUE_AMOUNT,TRANSACTION_DATE,LOADED_AT)
SELECT 'POS',TO_VARCHAR(p.SALE_ID),c.CUSTOMER_KEY,pr.PRODUCT_KEY,s.STORE_KEY,d.DATE_KEY,
 p.SALE_AMOUNT,
 ROUND(p.SALE_AMOUNT * TO_NUMBER((SELECT PARAMETER_VALUE FROM OPS.PIPELINE_PARAMETERS WHERE PARAMETER_NAME='DISCOUNT_RATE')),2),
 ROUND(p.SALE_AMOUNT * TO_NUMBER((SELECT PARAMETER_VALUE FROM OPS.PIPELINE_PARAMETERS WHERE PARAMETER_NAME='TAX_RATE')),2),
 p.SALE_AMOUNT,
 TO_DATE(p.LOADED_AT),p.LOADED_AT
FROM RAW.RAW_POS_SALES p
JOIN DIM_CUSTOMER c ON c.CUSTOMER_ID=p.CUSTOMER_ID AND c.IS_CURRENT
JOIN DIM_PRODUCT pr ON pr.PRODUCT_ID=p.PRODUCT_ID AND pr.IS_CURRENT
JOIN DIM_STORE s ON s.STORE_ID=p.STORE_ID
JOIN DIM_DATE d ON d.FULL_DATE=TO_DATE(p.LOADED_AT)
WHERE NOT EXISTS (SELECT 1 FROM FACT_SALES f WHERE f.SOURCE_TYPE='POS' AND f.SOURCE_TRANSACTION_ID=TO_VARCHAR(p.SALE_ID));

INSERT INTO FACT_SALES (
 SOURCE_TYPE,SOURCE_TRANSACTION_ID,CUSTOMER_KEY,PRODUCT_KEY,STORE_KEY,DATE_KEY,
 SALES_AMOUNT,DISCOUNT_AMOUNT,TAX_AMOUNT,REVENUE_AMOUNT,TRANSACTION_DATE,LOADED_AT)
SELECT 'ONLINE',TO_VARCHAR(o.ORDER_ID),c.CUSTOMER_KEY,pr.PRODUCT_KEY,
 NULL,d.DATE_KEY,o.ORDER_AMOUNT,
 ROUND(o.ORDER_AMOUNT * TO_NUMBER((SELECT PARAMETER_VALUE FROM OPS.PIPELINE_PARAMETERS WHERE PARAMETER_NAME='DISCOUNT_RATE')),2),
 ROUND(o.ORDER_AMOUNT * TO_NUMBER((SELECT PARAMETER_VALUE FROM OPS.PIPELINE_PARAMETERS WHERE PARAMETER_NAME='TAX_RATE')),2),
 o.ORDER_AMOUNT,o.ORDER_DATE,o.LOADED_AT
FROM RAW.RAW_ONLINE_ORDERS o
JOIN DIM_CUSTOMER c ON c.CUSTOMER_ID=o.CUSTOMER_ID AND c.IS_CURRENT
JOIN DIM_PRODUCT pr ON pr.PRODUCT_ID=o.PRODUCT_ID AND pr.IS_CURRENT
JOIN DIM_DATE d ON d.FULL_DATE=o.ORDER_DATE
WHERE NOT EXISTS (SELECT 1 FROM FACT_SALES f WHERE f.SOURCE_TYPE='ONLINE' AND f.SOURCE_TRANSACTION_ID=TO_VARCHAR(o.ORDER_ID));

INSERT INTO FACT_INVENTORY (DEVICE_ID,STORE_KEY,PRODUCT_KEY,QUANTITY_ON_HAND,LOG_DATE,LOADED_AT)
SELECT i.DEVICE_ID,s.STORE_KEY,p.PRODUCT_KEY,i.QUANTITY_ON_HAND,i.LOG_TIMESTAMP,i.LOADED_AT
FROM RAW.RAW_INVENTORY_DEVICE_LOGS i
JOIN DIM_STORE s ON s.STORE_ID=i.STORE_ID
JOIN DIM_PRODUCT p ON p.PRODUCT_ID=i.PRODUCT_ID AND p.IS_CURRENT
WHERE NOT EXISTS (
 SELECT 1 FROM FACT_INVENTORY f WHERE f.DEVICE_ID=i.DEVICE_ID AND f.LOG_DATE=i.LOG_TIMESTAMP
);
