-- Execute as ACCOUNTADMIN after replacing placeholders.
USE DATABASE GLOBRORETAIL_DW;

CREATE OR REPLACE STORAGE INTEGRATION GR_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/<SNOWFLAKE_S3_ROLE>'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<S3_BUCKET>/globo-retail/');

DESC STORAGE INTEGRATION GR_S3_INT;
-- Copy STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID from the output.
-- They are required in the AWS IAM trust relationship.
