USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE STG_POS_SALES
  URL='s3://<S3_BUCKET>/globo-retail/pos/'
  STORAGE_INTEGRATION=GR_S3_INT
  FILE_FORMAT=FF_CSV_STANDARD;

CREATE OR REPLACE STAGE STG_ONLINE_ORDERS
  URL='s3://<S3_BUCKET>/globo-retail/online/'
  STORAGE_INTEGRATION=GR_S3_INT
  FILE_FORMAT=FF_CSV_STANDARD;

CREATE OR REPLACE STAGE STG_PRODUCT_CATALOG
  URL='s3://<S3_BUCKET>/globo-retail/product/'
  STORAGE_INTEGRATION=GR_S3_INT
  FILE_FORMAT=FF_CSV_STANDARD;

CREATE OR REPLACE STAGE STG_INVENTORY_LOGS
  URL='s3://<S3_BUCKET>/globo-retail/inventory/'
  STORAGE_INTEGRATION=GR_S3_INT
  FILE_FORMAT=FF_CSV_STANDARD;

LIST @STG_POS_SALES;
LIST @STG_ONLINE_ORDERS;
LIST @STG_PRODUCT_CATALOG;
LIST @STG_INVENTORY_LOGS;
