USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA RAW;

CREATE OR REPLACE PIPE PIPE_POS_SALES
  AUTO_INGEST=TRUE
AS
COPY INTO RAW_POS_SALES (SALE_ID,CUSTOMER_ID,PRODUCT_ID,STORE_ID,SALE_AMOUNT,SOURCE_FILENAME,LOADED_AT)
FROM (
  SELECT $1,$2,$3,$4,$5,METADATA$FILENAME,CURRENT_TIMESTAMP()
  FROM @STG_POS_SALES
)
FILE_FORMAT=(FORMAT_NAME='FF_CSV_STANDARD')
ON_ERROR='CONTINUE';

CREATE OR REPLACE PIPE PIPE_ONLINE_ORDERS
  AUTO_INGEST=TRUE
AS
COPY INTO RAW_ONLINE_ORDERS (ORDER_ID,CUSTOMER_ID,PRODUCT_ID,ORDER_DATE,ORDER_AMOUNT,SOURCE_FILENAME,LOADED_AT)
FROM (
  SELECT $1,$2,$3,TRY_TO_DATE($4),$5,METADATA$FILENAME,CURRENT_TIMESTAMP()
  FROM @STG_ONLINE_ORDERS
)
FILE_FORMAT=(FORMAT_NAME='FF_CSV_STANDARD')
ON_ERROR='CONTINUE';

CREATE OR REPLACE PIPE PIPE_PRODUCT_CATALOG
  AUTO_INGEST=TRUE
AS
COPY INTO RAW_PRODUCT_CATALOG (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,SOURCE_FILENAME,LOADED_AT)
FROM (
  SELECT $1,$2,$3,$4,$5,METADATA$FILENAME,CURRENT_TIMESTAMP()
  FROM @STG_PRODUCT_CATALOG
)
FILE_FORMAT=(FORMAT_NAME='FF_CSV_STANDARD')
ON_ERROR='CONTINUE';

CREATE OR REPLACE PIPE PIPE_INVENTORY_LOGS
  AUTO_INGEST=TRUE
AS
COPY INTO RAW_INVENTORY_DEVICE_LOGS (DEVICE_ID,STORE_ID,PRODUCT_ID,QUANTITY_ON_HAND,LOG_TIMESTAMP,SOURCE_FILENAME,LOADED_AT)
FROM (
  SELECT $1,$2,$3,$4,TRY_TO_DATE($5),METADATA$FILENAME,CURRENT_TIMESTAMP()
  FROM @STG_INVENTORY_LOGS
)
FILE_FORMAT=(FORMAT_NAME='FF_CSV_STANDARD')
ON_ERROR='CONTINUE';

SHOW PIPES;
