USE DATABASE GLOBRORETAIL_DW;

-- Source counts should match the supplied demo files on the first load.
SELECT 'RAW_POS_SALES' OBJECT_NAME, COUNT(*) ROW_COUNT FROM RAW.RAW_POS_SALES
UNION ALL SELECT 'RAW_ONLINE_ORDERS', COUNT(*) FROM RAW.RAW_ONLINE_ORDERS
UNION ALL SELECT 'RAW_PRODUCT_CATALOG', COUNT(*) FROM RAW.RAW_PRODUCT_CATALOG
UNION ALL SELECT 'RAW_INVENTORY_DEVICE_LOGS', COUNT(*) FROM RAW.RAW_INVENTORY_DEVICE_LOGS;

-- Null and negative-value checks.
SELECT COUNT(*) AS NEGATIVE_POS FROM RAW.RAW_POS_SALES WHERE SALE_AMOUNT < 0;
SELECT COUNT(*) AS NEGATIVE_ONLINE FROM RAW.RAW_ONLINE_ORDERS WHERE ORDER_AMOUNT < 0;
SELECT COUNT(*) AS NEGATIVE_PRODUCT_PRICE FROM RAW.RAW_PRODUCT_CATALOG WHERE PRICE < 0;
SELECT COUNT(*) AS NEGATIVE_INVENTORY FROM RAW.RAW_INVENTORY_DEVICE_LOGS WHERE QUANTITY_ON_HAND < 0;

-- Referential checks against product catalog.
SELECT COUNT(*) AS POS_UNKNOWN_PRODUCTS
FROM RAW.RAW_POS_SALES p LEFT JOIN RAW.RAW_PRODUCT_CATALOG c ON p.PRODUCT_ID=c.PRODUCT_ID
WHERE c.PRODUCT_ID IS NULL;
SELECT COUNT(*) AS ONLINE_UNKNOWN_PRODUCTS
FROM RAW.RAW_ONLINE_ORDERS o LEFT JOIN RAW.RAW_PRODUCT_CATALOG c ON o.PRODUCT_ID=c.PRODUCT_ID
WHERE c.PRODUCT_ID IS NULL;
SELECT COUNT(*) AS INVENTORY_UNKNOWN_PRODUCTS
FROM RAW.RAW_INVENTORY_DEVICE_LOGS i LEFT JOIN RAW.RAW_PRODUCT_CATALOG c ON i.PRODUCT_ID=c.PRODUCT_ID
WHERE c.PRODUCT_ID IS NULL;

-- Core outputs.
SELECT COUNT(*) AS CUSTOMER_ROWS FROM CORE.DIM_CUSTOMER;
SELECT COUNT(*) AS PRODUCT_ROWS FROM CORE.DIM_PRODUCT WHERE IS_CURRENT;
SELECT COUNT(*) AS STORE_ROWS FROM CORE.DIM_STORE;
SELECT COUNT(*) AS DATE_ROWS FROM CORE.DIM_DATE;
SELECT COUNT(*) AS FACT_ROWS FROM CORE.FACT_SALES;

SELECT * FROM OPS.DATA_QUALITY_LOG ORDER BY CHECKED_AT DESC;
SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(TASK_NAME=>'GLOBRORETAIL_DW.OPS.TASK_01_RAW_TO_CLEAN')) ORDER BY SCHEDULED_TIME DESC LIMIT 20;
