USE DATABASE GLOBRORETAIL_DW;

CREATE OR REPLACE STREAM RAW.STM_POS_SALES ON TABLE RAW.RAW_POS_SALES SHOW_INITIAL_ROWS = TRUE;
CREATE OR REPLACE STREAM RAW.STM_ONLINE_ORDERS ON TABLE RAW.RAW_ONLINE_ORDERS SHOW_INITIAL_ROWS = TRUE;
CREATE OR REPLACE STREAM RAW.STM_PRODUCT_CATALOG ON TABLE RAW.RAW_PRODUCT_CATALOG SHOW_INITIAL_ROWS = TRUE;
CREATE OR REPLACE STREAM RAW.STM_INVENTORY_DEVICE_LOGS ON TABLE RAW.RAW_INVENTORY_DEVICE_LOGS SHOW_INITIAL_ROWS = TRUE;
