USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA CLEAN;

CREATE OR REPLACE TABLE CLEAN_POS_SALES LIKE RAW.RAW_POS_SALES;
CREATE OR REPLACE TABLE CLEAN_ONLINE_ORDERS LIKE RAW.RAW_ONLINE_ORDERS;
CREATE OR REPLACE TABLE CLEAN_PRODUCT_CATALOG LIKE RAW.RAW_PRODUCT_CATALOG;
CREATE OR REPLACE TABLE CLEAN_INVENTORY_DEVICE_LOGS LIKE RAW.RAW_INVENTORY_DEVICE_LOGS;
