-- 01_setup/00_database.sql
-- Foundation objects. Execute as ACCOUNTADMIN or a role with equivalent privileges.

CREATE DATABASE IF NOT EXISTS GLOBRORETAIL_DW;
CREATE SCHEMA IF NOT EXISTS GLOBRORETAIL_DW.RAW;
CREATE SCHEMA IF NOT EXISTS GLOBRORETAIL_DW.CLEAN;
CREATE SCHEMA IF NOT EXISTS GLOBRORETAIL_DW.CORE;
CREATE SCHEMA IF NOT EXISTS GLOBRORETAIL_DW.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS GLOBRORETAIL_DW.SECURITY;
CREATE SCHEMA IF NOT EXISTS GLOBRORETAIL_DW.OPS;

CREATE WAREHOUSE IF NOT EXISTS GR_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS GR_TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS GR_BI_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE GR_WH;
USE DATABASE GLOBRORETAIL_DW;

CREATE OR REPLACE TABLE OPS.PIPELINE_RUN_LOG (
  RUN_ID NUMBER AUTOINCREMENT,
  PIPELINE_NAME STRING,
  STEP_NAME STRING,
  STATUS STRING,
  ROW_COUNT NUMBER,
  ERROR_MESSAGE STRING,
  STARTED_AT TIMESTAMP_LTZ,
  ENDED_AT TIMESTAMP_LTZ,
  QUERY_ID STRING
);

CREATE OR REPLACE TABLE OPS.DATA_QUALITY_LOG (
  CHECK_ID NUMBER AUTOINCREMENT,
  CHECK_NAME STRING,
  TARGET_OBJECT STRING,
  EXPECTED_VALUE STRING,
  ACTUAL_VALUE STRING,
  STATUS STRING,
  CHECKED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE OPS.PIPELINE_PARAMETERS (
  PARAMETER_NAME STRING PRIMARY KEY,
  PARAMETER_VALUE STRING,
  DESCRIPTION STRING
);

INSERT OVERWRITE INTO OPS.PIPELINE_PARAMETERS VALUES
('TAX_RATE','0.18','Demo assumption because source files do not contain tax_rate.'),
('DISCOUNT_RATE','0','Demo assumption because source files do not contain discount fields.'),
('LOW_STOCK_THRESHOLD','20','Inventory alert threshold for analytics demonstration.');
