USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FF_CSV_STANDARD
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL','null','');

CREATE OR REPLACE FILE FORMAT FF_CSV_NO_HEADER
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 0
  NULL_IF = ('NULL','null','');
