
CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_KEY INT PRIMARY KEY,
  CUSTOMER_ID STRING,
  CUSTOMER_NAME STRING,
  CUSTOMER_SEGMENT STRING,
  COUNTRY STRING
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
  PRODUCT_KEY INT PRIMARY KEY,
  PRODUCT_ID STRING,
  PRODUCT_NAME STRING,
  CATEGORY STRING,
  PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE DIM_STORE (
  STORE_KEY INT PRIMARY KEY,
  STORE_ID STRING,
  STORE_NAME STRING,
  CITY STRING,
  STATE STRING
);

CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY INT PRIMARY KEY,
  FULL_DATE DATE,
  YEAR INT,
  MONTH INT,
  DAY INT
);

CREATE OR REPLACE TABLE FACT_SALES (
  SALES_KEY INT PRIMARY KEY,
  CUSTOMER_KEY INT,
  PRODUCT_KEY INT,
  STORE_KEY INT,
  DATE_KEY INT,
  SALES_AMOUNT NUMBER(12,2),
  CONSTRAINT FK_CUST FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
  CONSTRAINT FK_PROD FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
  CONSTRAINT FK_STORE FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY),
  CONSTRAINT FK_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY)
);
