USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_POS_SALES (
  SALE_ID NUMBER,
  CUSTOMER_ID STRING,
  PRODUCT_ID STRING,
  STORE_ID STRING,
  SALE_AMOUNT NUMBER(12,2),
  SOURCE_FILENAME STRING,
  LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE RAW_ONLINE_ORDERS (
  ORDER_ID NUMBER,
  CUSTOMER_ID STRING,
  PRODUCT_ID STRING,
  ORDER_DATE DATE,
  ORDER_AMOUNT NUMBER(12,2),
  SOURCE_FILENAME STRING,
  LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE RAW_PRODUCT_CATALOG (
  PRODUCT_ID STRING,
  PRODUCT_NAME STRING,
  CATEGORY STRING,
  PRICE NUMBER(10,2),
  STATUS STRING,
  SOURCE_FILENAME STRING,
  LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE RAW_INVENTORY_DEVICE_LOGS (
  DEVICE_ID STRING,
  STORE_ID STRING,
  PRODUCT_ID STRING,
  QUANTITY_ON_HAND NUMBER,
  LOG_TIMESTAMP DATE,
  SOURCE_FILENAME STRING,
  LOADED_AT TIMESTAMP_LTZ
);

CREATE OR REPLACE TABLE RAW_INGESTION_LOG (
  LOG_ID NUMBER AUTOINCREMENT,
  SOURCE_FILENAME STRING,
  SOURCE_TYPE STRING,
  TARGET_TABLE STRING,
  STATUS STRING,
  ROW_COUNT NUMBER,
  LOAD_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ERROR_MESSAGE STRING
);
