USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA OPS;

CREATE OR REPLACE PROCEDURE SP_LOG_PIPELINE(P_PIPELINE STRING, P_STEP STRING, P_STATUS STRING, P_ROW_COUNT NUMBER, P_ERROR STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
try {
  var sql = `INSERT INTO GLOBRORETAIL_DW.OPS.PIPELINE_RUN_LOG
             (PIPELINE_NAME,STEP_NAME,STATUS,ROW_COUNT,ERROR_MESSAGE,STARTED_AT,ENDED_AT)
             VALUES (?,?,?,?,?,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP())`;
  snowflake.createStatement({sqlText: sql, binds:[P_PIPELINE,P_STEP,P_STATUS,P_ROW_COUNT,P_ERROR]}).execute();
  return 'LOGGED: ' + P_STEP;
} catch (err) {
  return 'LOGGING_ERROR: ' + err.message;
}
$$;

CREATE OR REPLACE PROCEDURE SP_MERGE_CUSTOMER_SCD2()
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
try {
  var closeSql = `UPDATE GLOBRORETAIL_DW.CORE.DIM_CUSTOMER c
                  SET EFFECTIVE_TO=CURRENT_TIMESTAMP(), IS_CURRENT=FALSE
                  FROM (
                    SELECT CUSTOMER_ID,
                           MD5(CUSTOMER_ID || '|' || CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),3) WHEN 0 THEN 'STANDARD' WHEN 1 THEN 'PREMIUM' ELSE 'BASIC' END || '|' || CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),4) WHEN 0 THEN 'India' WHEN 1 THEN 'USA' WHEN 2 THEN 'UK' ELSE 'UAE' END) AS RECORD_HASH
                    FROM (
                      SELECT DISTINCT CUSTOMER_ID FROM GLOBRORETAIL_DW.CLEAN.CLEAN_POS_SALES
                      UNION SELECT DISTINCT CUSTOMER_ID FROM GLOBRORETAIL_DW.CLEAN.CLEAN_ONLINE_ORDERS
                    )
                  ) s
                  WHERE c.CUSTOMER_ID=s.CUSTOMER_ID
                    AND c.IS_CURRENT=TRUE
                    AND NVL(c.RECORD_HASH,'')<>s.RECORD_HASH`;
  snowflake.createStatement({sqlText:closeSql}).execute();

  var insertSql = `INSERT INTO GLOBRORETAIL_DW.CORE.DIM_CUSTOMER
    (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SEGMENT,COUNTRY,CUSTOMER_EMAIL,PHONE_NUMBER,PAYMENT_CARD_HASH,EFFECTIVE_FROM,IS_CURRENT,RECORD_HASH)
    SELECT s.CUSTOMER_ID,s.CUSTOMER_NAME,s.CUSTOMER_SEGMENT,s.COUNTRY,s.CUSTOMER_EMAIL,s.PHONE_NUMBER,s.PAYMENT_CARD_HASH,CURRENT_TIMESTAMP(),TRUE,s.RECORD_HASH
    FROM (
      SELECT DISTINCT CUSTOMER_ID,
        'Customer_'||CUSTOMER_ID CUSTOMER_NAME,
        CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),3) WHEN 0 THEN 'STANDARD' WHEN 1 THEN 'PREMIUM' ELSE 'BASIC' END CUSTOMER_SEGMENT,
        CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),4) WHEN 0 THEN 'India' WHEN 1 THEN 'USA' WHEN 2 THEN 'UK' ELSE 'UAE' END COUNTRY,
        LOWER(CUSTOMER_ID)||'@example.demo' CUSTOMER_EMAIL,
        '+91-90000-'||LPAD(RIGHT(CUSTOMER_ID,5),5,'0') PHONE_NUMBER,
        SHA2('CARD-'||CUSTOMER_ID,256) PAYMENT_CARD_HASH,
        MD5(CUSTOMER_ID||'|'||CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),3) WHEN 0 THEN 'STANDARD' WHEN 1 THEN 'PREMIUM' ELSE 'BASIC' END||'|'||CASE MOD(TRY_TO_NUMBER(RIGHT(CUSTOMER_ID,4)),4) WHEN 0 THEN 'India' WHEN 1 THEN 'USA' WHEN 2 THEN 'UK' ELSE 'UAE' END) RECORD_HASH
      FROM (SELECT DISTINCT CUSTOMER_ID FROM GLOBRORETAIL_DW.CLEAN.CLEAN_POS_SALES UNION SELECT DISTINCT CUSTOMER_ID FROM GLOBRORETAIL_DW.CLEAN.CLEAN_ONLINE_ORDERS)
    ) s
    LEFT JOIN GLOBRORETAIL_DW.CORE.DIM_CUSTOMER c
      ON c.CUSTOMER_ID=s.CUSTOMER_ID AND c.IS_CURRENT=TRUE
    WHERE c.CUSTOMER_KEY IS NULL`;
  var rs=snowflake.createStatement({sqlText:insertSql}).execute();

  var productSql = `MERGE INTO GLOBRORETAIL_DW.CORE.DIM_PRODUCT tgt
    USING (SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,
                  MD5(PRODUCT_ID||'|'||PRODUCT_NAME||'|'||CATEGORY||'|'||PRICE||'|'||STATUS) RECORD_HASH
           FROM GLOBRORETAIL_DW.CLEAN.CLEAN_PRODUCT_CATALOG
           QUALIFY ROW_NUMBER() OVER(PARTITION BY PRODUCT_ID ORDER BY LOADED_AT DESC)=1) src
    ON tgt.PRODUCT_ID=src.PRODUCT_ID AND tgt.IS_CURRENT=TRUE
    WHEN MATCHED AND NVL(tgt.RECORD_HASH,'')<>src.RECORD_HASH
      THEN UPDATE SET EFFECTIVE_TO=CURRENT_TIMESTAMP(),IS_CURRENT=FALSE
    WHEN NOT MATCHED THEN INSERT
      (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,EFFECTIVE_FROM,IS_CURRENT,RECORD_HASH)
      VALUES(src.PRODUCT_ID,src.PRODUCT_NAME,src.CATEGORY,src.PRICE,src.STATUS,CURRENT_TIMESTAMP(),TRUE,src.RECORD_HASH)`;
  snowflake.createStatement({sqlText:productSql}).execute();

  var productInsertSql = `INSERT INTO GLOBRORETAIL_DW.CORE.DIM_PRODUCT
    (PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,EFFECTIVE_FROM,IS_CURRENT,RECORD_HASH)
    SELECT s.PRODUCT_ID,s.PRODUCT_NAME,s.CATEGORY,s.PRICE,s.STATUS,CURRENT_TIMESTAMP(),TRUE,s.RECORD_HASH
    FROM (SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,
                 MD5(PRODUCT_ID||'|'||PRODUCT_NAME||'|'||CATEGORY||'|'||PRICE||'|'||STATUS) RECORD_HASH
          FROM GLOBRORETAIL_DW.CLEAN.CLEAN_PRODUCT_CATALOG
          QUALIFY ROW_NUMBER() OVER(PARTITION BY PRODUCT_ID ORDER BY LOADED_AT DESC)=1) s
    LEFT JOIN GLOBRORETAIL_DW.CORE.DIM_PRODUCT p
      ON p.PRODUCT_ID=s.PRODUCT_ID AND p.IS_CURRENT=TRUE
    WHERE p.PRODUCT_KEY IS NULL`;
  snowflake.createStatement({sqlText:productInsertSql}).execute();
  return 'SUCCESS: SCD2 customer/product merge completed';
} catch (err) {
  snowflake.createStatement({sqlText:`INSERT INTO GLOBRORETAIL_DW.OPS.PIPELINE_RUN_LOG
    (PIPELINE_NAME,STEP_NAME,STATUS,ERROR_MESSAGE,STARTED_AT,ENDED_AT)
    VALUES ('GLOBO_RETAIL','SCD2_CUSTOMER','FAILED',?,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP())`,binds:[err.message]}).execute();
  return 'FAILED: ' + err.message;
}
$$;

CREATE OR REPLACE PROCEDURE SP_RUN_DATA_QUALITY()
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
try {
  var checks = [
    [`POS_RAW_COUNT`,`GLOBRORETAIL_DW.RAW.RAW_POS_SALES`,`SELECT COUNT(*) FROM GLOBRORETAIL_DW.RAW.RAW_POS_SALES`,`1000`],
    [`ONLINE_RAW_COUNT`,`GLOBRORETAIL_DW.RAW.RAW_ONLINE_ORDERS`,`SELECT COUNT(*) FROM GLOBRORETAIL_DW.RAW.RAW_ONLINE_ORDERS`,`1000`],
    [`PRODUCT_RAW_COUNT`,`GLOBRORETAIL_DW.RAW.RAW_PRODUCT_CATALOG`,`SELECT COUNT(*) FROM GLOBRORETAIL_DW.RAW.RAW_PRODUCT_CATALOG`,`1000`],
    [`INVENTORY_RAW_COUNT`,`GLOBRORETAIL_DW.RAW.RAW_INVENTORY_DEVICE_LOGS`,`SELECT COUNT(*) FROM GLOBRORETAIL_DW.RAW.RAW_INVENTORY_DEVICE_LOGS`,`1000`],
    [`NEGATIVE_FACT_AMOUNT`,`GLOBRORETAIL_DW.CORE.FACT_SALES`,`SELECT COUNT(*) FROM GLOBRORETAIL_DW.CORE.FACT_SALES WHERE SALES_AMOUNT < 0`,`0`],
    [`NULL_FACT_REVENUE`,`GLOBRORETAIL_DW.CORE.FACT_SALES`,`SELECT COUNT(*) FROM GLOBRORETAIL_DW.CORE.FACT_SALES WHERE REVENUE_AMOUNT IS NULL`,`0`]
  ];
  for (var i=0;i<checks.length;i++) {
    var rs=snowflake.createStatement({sqlText:checks[i][2]}).execute(); rs.next(); var actual=rs.getColumnValue(1).toString();
    var status=(actual===checks[i][3] || (checks[i][0].endsWith('COUNT') && Number(actual)>=Number(checks[i][3])))?'PASS':'FAIL';
    snowflake.createStatement({sqlText:`INSERT INTO GLOBRORETAIL_DW.OPS.DATA_QUALITY_LOG
      (CHECK_NAME,TARGET_OBJECT,EXPECTED_VALUE,ACTUAL_VALUE,STATUS)
      VALUES (?,?,?,?,?)`,binds:[checks[i][0],checks[i][1],checks[i][3],actual,status]}).execute();
  }
  return 'SUCCESS: DQ checks executed';
} catch (err) {
  return 'FAILED: ' + err.message;
}
$$;

CREATE OR REPLACE PROCEDURE SP_REFRESH_ANALYTICS()
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
try {
  snowflake.createStatement({sqlText:`TRUNCATE TABLE GLOBRORETAIL_DW.CORE.ML_FEATURES_HOURLY_STORE_REVENUE`}).execute();
  snowflake.createStatement({sqlText:`INSERT INTO GLOBRORETAIL_DW.CORE.ML_FEATURES_HOURLY_STORE_REVENUE
    SELECT f.TRANSACTION_DATE,s.STORE_KEY,SUM(f.REVENUE_AMOUNT),COUNT(*),AVG(f.REVENUE_AMOUNT),
      COALESCE((SELECT COUNT(*) FROM GLOBRORETAIL_DW.CORE.FACT_INVENTORY i WHERE i.STORE_KEY=s.STORE_KEY AND i.QUANTITY_ON_HAND < 20),0),
      LAG(SUM(f.REVENUE_AMOUNT)) OVER(PARTITION BY s.STORE_KEY ORDER BY f.TRANSACTION_DATE),
      SUM(SUM(f.REVENUE_AMOUNT)) OVER(PARTITION BY s.STORE_KEY ORDER BY f.TRANSACTION_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW),
      0
    FROM GLOBRORETAIL_DW.CORE.FACT_SALES f
    LEFT JOIN GLOBRORETAIL_DW.CORE.DIM_STORE s ON f.STORE_KEY=s.STORE_KEY
    GROUP BY f.TRANSACTION_DATE,s.STORE_KEY`}).execute();
  snowflake.createStatement({sqlText:`ALTER DYNAMIC TABLE GLOBRORETAIL_DW.ANALYTICS.DT_DAILY_STORE_REVENUE REFRESH`}).execute();
  return 'SUCCESS: analytics and dynamic table refreshed';
} catch (err) { return 'FAILED: ' + err.message; }
$$;
