USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA CORE;

-- Clustering is deliberately on transaction date + store. The supplied demo data is only
-- 2,000 sales rows, so measurable pruning gains should be demonstrated on a larger clone/load.
ALTER TABLE FACT_SALES CLUSTER BY (TRANSACTION_DATE, STORE_KEY);

-- Before/after comparison queries. Record execution time and partitions scanned in Snowsight.
-- Baseline:
SELECT STORE_KEY, SUM(REVENUE_AMOUNT)
FROM FACT_SALES
WHERE TRANSACTION_DATE BETWEEN '2024-01-01' AND '2024-03-31'
GROUP BY STORE_KEY;

-- Selective version using both clustering dimensions:
SELECT STORE_KEY, SUM(REVENUE_AMOUNT)
FROM FACT_SALES
WHERE TRANSACTION_DATE BETWEEN '2024-01-01' AND '2024-03-31'
  AND STORE_KEY=1
GROUP BY STORE_KEY;

CREATE WAREHOUSE IF NOT EXISTS GR_CONCURRENCY_WH
  WAREHOUSE_SIZE='XSMALL'
  MIN_CLUSTER_COUNT=1
  MAX_CLUSTER_COUNT=3
  SCALING_POLICY='STANDARD'
  AUTO_SUSPEND=60
  AUTO_RESUME=TRUE
  INITIALLY_SUSPENDED=TRUE;

CREATE OR REPLACE RESOURCE MONITOR GR_RESOURCE_MONITOR
  WITH CREDIT_QUOTA=100
  FREQUENCY=MONTHLY
  START_TIMESTAMP=IMMEDIATELY
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE GR_CONCURRENCY_WH SET RESOURCE_MONITOR=GR_RESOURCE_MONITOR;
