USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA ANALYTICS;

-- Requires access to SNOWFLAKE.ACCOUNT_USAGE or an equivalent monitoring role.
CREATE OR REPLACE VIEW V_QUERY_HISTORY_ANALYSIS AS
SELECT QUERY_ID,USER_NAME,ROLE_NAME,WAREHOUSE_NAME,
       START_TIME,END_TIME,TOTAL_ELAPSED_TIME,
       BYTES_SCANNED,BYTES_SPILLED_TO_LOCAL_STORAGE,
       PARTITIONS_SCANNED,PARTITIONS_TOTAL,
       CASE WHEN PARTITIONS_TOTAL=0 THEN NULL
            ELSE ROUND(100*(1-(PARTITIONS_SCANNED/PARTITIONS_TOTAL)),2) END AS PRUNING_PCT,
       QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(DAY,-7,CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;

SELECT * FROM V_QUERY_HISTORY_ANALYSIS LIMIT 100;
