USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA ANALYTICS;

CREATE OR ALTER DYNAMIC TABLE DT_DAILY_STORE_REVENUE
  TARGET_LAG='10 minutes'
  WAREHOUSE=GR_BI_WH
  REFRESH_MODE=FULL
AS
SELECT f.TRANSACTION_DATE,
       s.STORE_KEY,
       s.STORE_ID,
       s.REGION,
       SUM(f.REVENUE_AMOUNT) AS TOTAL_REVENUE,
       COUNT(*) AS TRANSACTION_COUNT,
       AVG(f.REVENUE_AMOUNT) AS AVG_TRANSACTION_VALUE
FROM CORE.FACT_SALES f
LEFT JOIN CORE.DIM_STORE s ON f.STORE_KEY=s.STORE_KEY
GROUP BY f.TRANSACTION_DATE,s.STORE_KEY,s.STORE_ID,s.REGION;

CREATE OR REPLACE MATERIALIZED VIEW MV_DAILY_REVENUE AS
SELECT TRANSACTION_DATE,
       SOURCE_TYPE,
       SUM(REVENUE_AMOUNT) AS TOTAL_REVENUE,
       COUNT(*) AS TRANSACTION_COUNT
FROM CORE.FACT_SALES
GROUP BY TRANSACTION_DATE,SOURCE_TYPE;

CREATE OR REPLACE VIEW V_EXECUTIVE_SALES AS
SELECT d.FULL_DATE,
       f.SOURCE_TYPE,
       SUM(f.REVENUE_AMOUNT) TOTAL_REVENUE,
       COUNT(*) TRANSACTION_COUNT,
       AVG(f.REVENUE_AMOUNT) AVG_TRANSACTION_VALUE
FROM CORE.FACT_SALES f
JOIN CORE.DIM_DATE d ON d.DATE_KEY=f.DATE_KEY
GROUP BY d.FULL_DATE,f.SOURCE_TYPE;
