USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA OPS;

CREATE OR REPLACE TASK TASK_01_RAW_TO_CLEAN
  WAREHOUSE=GR_TRANSFORM_WH
  WHEN SYSTEM$STREAM_HAS_DATA('GLOBRORETAIL_DW.RAW.STM_POS_SALES')
    OR SYSTEM$STREAM_HAS_DATA('GLOBRORETAIL_DW.RAW.STM_ONLINE_ORDERS')
    OR SYSTEM$STREAM_HAS_DATA('GLOBRORETAIL_DW.RAW.STM_PRODUCT_CATALOG')
    OR SYSTEM$STREAM_HAS_DATA('GLOBRORETAIL_DW.RAW.STM_INVENTORY_DEVICE_LOGS')
AS
BEGIN
  -- Apply DELETE actions first. This is required for UPDATE records, which appear as
  -- a DELETE of the old version followed by an INSERT of the new version in a standard stream.
  DELETE FROM GLOBRORETAIL_DW.CLEAN.CLEAN_POS_SALES c USING GLOBRORETAIL_DW.RAW.STM_POS_SALES s
    WHERE s.METADATA$ACTION='DELETE' AND c.SALE_ID=s.SALE_ID;
  DELETE FROM GLOBRORETAIL_DW.CLEAN.CLEAN_ONLINE_ORDERS c USING GLOBRORETAIL_DW.RAW.STM_ONLINE_ORDERS s
    WHERE s.METADATA$ACTION='DELETE' AND c.ORDER_ID=s.ORDER_ID;
  DELETE FROM GLOBRORETAIL_DW.CLEAN.CLEAN_PRODUCT_CATALOG c USING GLOBRORETAIL_DW.RAW.STM_PRODUCT_CATALOG s
    WHERE s.METADATA$ACTION='DELETE' AND c.PRODUCT_ID=s.PRODUCT_ID;
  DELETE FROM GLOBRORETAIL_DW.CLEAN.CLEAN_INVENTORY_DEVICE_LOGS c USING GLOBRORETAIL_DW.RAW.STM_INVENTORY_DEVICE_LOGS s
    WHERE s.METADATA$ACTION='DELETE' AND c.DEVICE_ID=s.DEVICE_ID AND c.LOG_TIMESTAMP=s.LOG_TIMESTAMP;

  INSERT INTO GLOBRORETAIL_DW.CLEAN.CLEAN_POS_SALES
  SELECT SALE_ID,CUSTOMER_ID,PRODUCT_ID,STORE_ID,SALE_AMOUNT,SOURCE_FILENAME,LOADED_AT
  FROM GLOBRORETAIL_DW.RAW.STM_POS_SALES WHERE METADATA$ACTION='INSERT';
  INSERT INTO GLOBRORETAIL_DW.CLEAN.CLEAN_ONLINE_ORDERS
  SELECT ORDER_ID,CUSTOMER_ID,PRODUCT_ID,ORDER_DATE,ORDER_AMOUNT,SOURCE_FILENAME,LOADED_AT
  FROM GLOBRORETAIL_DW.RAW.STM_ONLINE_ORDERS WHERE METADATA$ACTION='INSERT';
  INSERT INTO GLOBRORETAIL_DW.CLEAN.CLEAN_PRODUCT_CATALOG
  SELECT PRODUCT_ID,PRODUCT_NAME,CATEGORY,PRICE,STATUS,SOURCE_FILENAME,LOADED_AT
  FROM GLOBRORETAIL_DW.RAW.STM_PRODUCT_CATALOG WHERE METADATA$ACTION='INSERT';
  INSERT INTO GLOBRORETAIL_DW.CLEAN.CLEAN_INVENTORY_DEVICE_LOGS
  SELECT DEVICE_ID,STORE_ID,PRODUCT_ID,QUANTITY_ON_HAND,LOG_TIMESTAMP,SOURCE_FILENAME,LOADED_AT
  FROM GLOBRORETAIL_DW.RAW.STM_INVENTORY_DEVICE_LOGS WHERE METADATA$ACTION='INSERT';

  INSERT INTO GLOBRORETAIL_DW.OPS.PIPELINE_RUN_LOG
  (PIPELINE_NAME,STEP_NAME,STATUS,ROW_COUNT,STARTED_AT,ENDED_AT)
  VALUES ('GLOBO_RETAIL','RAW_TO_CLEAN','SUCCESS',SQLROWCOUNT,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
END;

CREATE OR REPLACE TASK TASK_02_SCD2_DIMENSIONS
  WAREHOUSE=GR_TRANSFORM_WH
  AFTER TASK_01_RAW_TO_CLEAN
AS
CALL GLOBRORETAIL_DW.OPS.SP_MERGE_CUSTOMER_SCD2();

CREATE OR REPLACE TASK TASK_03_LOAD_FACTS
  WAREHOUSE=GR_TRANSFORM_WH
  AFTER TASK_02_SCD2_DIMENSIONS
AS
BEGIN
  INSERT INTO GLOBRORETAIL_DW.CORE.FACT_SALES
  (SOURCE_TYPE,SOURCE_TRANSACTION_ID,CUSTOMER_KEY,PRODUCT_KEY,STORE_KEY,DATE_KEY,SALES_AMOUNT,DISCOUNT_AMOUNT,TAX_AMOUNT,REVENUE_AMOUNT,TRANSACTION_DATE,LOADED_AT)
  SELECT 'POS',TO_VARCHAR(p.SALE_ID),c.CUSTOMER_KEY,pr.PRODUCT_KEY,s.STORE_KEY,d.DATE_KEY,p.SALE_AMOUNT,0,ROUND(p.SALE_AMOUNT*0.18,2),p.SALE_AMOUNT,TO_DATE(p.LOADED_AT),p.LOADED_AT
  FROM GLOBRORETAIL_DW.CLEAN.CLEAN_POS_SALES p
  JOIN GLOBRORETAIL_DW.CORE.DIM_CUSTOMER c ON c.CUSTOMER_ID=p.CUSTOMER_ID AND c.IS_CURRENT
  JOIN GLOBRORETAIL_DW.CORE.DIM_PRODUCT pr ON pr.PRODUCT_ID=p.PRODUCT_ID AND pr.IS_CURRENT
  JOIN GLOBRORETAIL_DW.CORE.DIM_STORE s ON s.STORE_ID=p.STORE_ID
  JOIN GLOBRORETAIL_DW.CORE.DIM_DATE d ON d.FULL_DATE=TO_DATE(p.LOADED_AT)
  WHERE NOT EXISTS(SELECT 1 FROM GLOBRORETAIL_DW.CORE.FACT_SALES f WHERE f.SOURCE_TYPE='POS' AND f.SOURCE_TRANSACTION_ID=TO_VARCHAR(p.SALE_ID));

  INSERT INTO GLOBRORETAIL_DW.CORE.FACT_SALES
  (SOURCE_TYPE,SOURCE_TRANSACTION_ID,CUSTOMER_KEY,PRODUCT_KEY,STORE_KEY,DATE_KEY,SALES_AMOUNT,DISCOUNT_AMOUNT,TAX_AMOUNT,REVENUE_AMOUNT,TRANSACTION_DATE,LOADED_AT)
  SELECT 'ONLINE',TO_VARCHAR(o.ORDER_ID),c.CUSTOMER_KEY,pr.PRODUCT_KEY,NULL,d.DATE_KEY,o.ORDER_AMOUNT,0,ROUND(o.ORDER_AMOUNT*0.18,2),o.ORDER_AMOUNT,o.ORDER_DATE,o.LOADED_AT
  FROM GLOBRORETAIL_DW.CLEAN.CLEAN_ONLINE_ORDERS o
  JOIN GLOBRORETAIL_DW.CORE.DIM_CUSTOMER c ON c.CUSTOMER_ID=o.CUSTOMER_ID AND c.IS_CURRENT
  JOIN GLOBRORETAIL_DW.CORE.DIM_PRODUCT pr ON pr.PRODUCT_ID=o.PRODUCT_ID AND pr.IS_CURRENT
  JOIN GLOBRORETAIL_DW.CORE.DIM_DATE d ON d.FULL_DATE=o.ORDER_DATE
  WHERE NOT EXISTS(SELECT 1 FROM GLOBRORETAIL_DW.CORE.FACT_SALES f WHERE f.SOURCE_TYPE='ONLINE' AND f.SOURCE_TRANSACTION_ID=TO_VARCHAR(o.ORDER_ID));
END;

CREATE OR REPLACE TASK TASK_04_REFRESH_ANALYTICS
  WAREHOUSE=GR_BI_WH
  AFTER TASK_03_LOAD_FACTS
AS
CALL GLOBRORETAIL_DW.OPS.SP_REFRESH_ANALYTICS();

CREATE OR REPLACE TASK TASK_05_DATA_QUALITY
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL'
  AFTER TASK_04_REFRESH_ANALYTICS
AS
CALL GLOBRORETAIL_DW.OPS.SP_RUN_DATA_QUALITY();

-- Keep the DAG suspended until all setup scripts, dimensions, procedures and analytics objects are deployed.
-- Run 99_start_pipeline.sql only after the deployment checklist is complete.
