-- Replace only TASK_05 definition if your account rejects SERVERLESS_TASK_* parameters.
-- Current Snowflake syntax supports USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE for serverless tasks.
USE DATABASE GLOBRORETAIL_DW;
USE SCHEMA OPS;

CREATE OR REPLACE TASK TASK_05_DATA_QUALITY
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL'
  AFTER TASK_04_REFRESH_ANALYTICS
AS
CALL GLOBRORETAIL_DW.OPS.SP_RUN_DATA_QUALITY();

ALTER TASK TASK_05_DATA_QUALITY RESUME;
